# Owned by grafana-delivery-squad
# Intended to be dropped into the security patch repo, Ex: grafana/grafana-security-patches
name: Create security patch
run-name: create-security-patch
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - "main"
      - "v*.*.*"

# This is run before the pull request has been merged, so we'll run against the src branch
jobs:
  trigger_downstream_create_security_patch:
    concurrency: create-patch-${{ github.ref_name }}
    uses: grafana/security-patch-actions/.github/workflows/create-patch.yml@develop
    if: github.repository == 'grafana/grafana-ci-sandbox-security-mirror' && github.event.review.state == 'approved'
    with:
      repo: "${{ github.repository }}"
      src_ref: "${{ github.head_ref }}" # this is the source branch name, Ex: "feature/newthing"
      patch_ref: "${{ github.base_ref }}" # this is the target branch name, Ex: "main"
      patch_repo: "grafana/grafana-ci-sandbox-security-patches"
    secrets: inherit

